### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by senzacionale** [mikesir87/helm-charts#19]
Hi, I found this nice helm charts for docker-compose. But I also see that is not maintained any more. Is this project still alive and ready to use?

Thank you

**Comment by mikesir87** [comment]
Hey there! For the most part, it's fairly complete as-is, minus a few corner cases. Is there anything you wish it'd do or bugs you've run into?

**Comment by senzacionale** [comment]
Hi. No for now everything is fine and working. I like it. Only think I am missing is 'depends_on' but I can survive without it 👍

Can I use helm v3 with this helm charts? Currently I am using v1 but is deprecated. 

Thank you

**Comment by mikesir87** [comment]
Thanks for the feedback! 

> Only think I am missing is 'depends_on'

There's not really a good way to implement `depends_on`, as there isn't a mechanism to do that in Kubernetes. The only valid use case I _could_ implement would be for initContainers, but that's a very different use case that what folks typically use `depends_on` in Compose.

> Can I use helm v3 with this helm charts?

Yes! It was designed for v3, as v2 was already deprecated when I started working on it. I'd definitely encourage updating as Helm's security model is much better going forward.

I'm going to go ahead and close the issue, but feel free to keep the conversation going if you have more questions!
